/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE parcelsBase PLEASE EDIT ../parcels.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
import { Customers } from '../customers';

/**
 * This is the model of parcels object
 *
 */
export class ParcelsBase {

    constructor() { }

    public _id: string;
    public Destination: string;
    public Height?: number;
    public Length?: number;
    public ParcelContents: string;
    public Status?: string;
    public Type?: string;
    public Weight: number;
    public Width?: number;
    // Relations customer
    public customer: Customers | string;
}
