/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE customersBaseService PLEASE EDIT ../customers.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Customers } from '../../domain/parcelum_db/customers';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../customers.service.ts
 */

/*
 * SCHEMA DB customers
 *
	{
		Adress: {
			type: 'String',
			required : true
		},
		ContactNumber: {
			type: 'Number'
		},
		DateofBirth: {
			type: 'Date'
		},
		Email: {
			type: 'String'
		},
		FullName: {
			type: 'String',
			required : true
		},
		Title: {
			type: 'String',
			enum : ["Dr", "Miss", "Mr", "Mrs", "Ms"]
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		customer: {
			type: Schema.ObjectId,
			ref : "parcels"
		},
	}
 *
 */
@Injectable()
export class CustomersBaseService {

    contextUrl: string = environment.endpoint + '/customers';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * customersService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Customers): Observable<Customers> {
        return this.http
            .post<Customers>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * customersService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * customersService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Customers> {
        return this.http
            .get<Customers>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * customersService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Customers[]> {
        return this.http
            .get<Customers[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * customersService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Customers): Observable<Customers> {
        return this.http
            .post<Customers>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
