/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE parcelsBaseService PLEASE EDIT ../parcels.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Parcels } from '../../domain/parcelum_db/parcels';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../parcels.service.ts
 */

/*
 * SCHEMA DB parcels
 *
	{
		Destination: {
			type: 'String',
			required : true
		},
		Height: {
			type: 'Number'
		},
		Length: {
			type: 'Number'
		},
		ParcelContents: {
			type: 'String',
			required : true
		},
		Status: {
			type: 'String',
			enum : ["Delivered", "Failed", "Pending"]
		},
		Type: {
			type: 'String',
			enum : ["Letter", "Parcel"]
		},
		Weight: {
			type: 'Number',
			required : true
		},
		Width: {
			type: 'Number'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		customer: {
			type: Schema.ObjectId,
			ref : "parcels"
		},
	}
 *
 */
@Injectable()
export class ParcelsBaseService {

    contextUrl: string = environment.endpoint + '/parcels';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * parcelsService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Parcels): Observable<Parcels> {
        return this.http
            .post<Parcels>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * parcelsService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * parcelsService.findBycustomer
    *   @description CRUD ACTION findBycustomer
    *   @param Objectid key Id of model to search for
    *
    */
    findByCustomer(id: string): Observable<Parcels[]> {
        return this.http
            .get<Parcels[]>(this.contextUrl + '/findBycustomer/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * parcelsService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Parcels> {
        return this.http
            .get<Parcels>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * parcelsService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Parcels[]> {
        return this.http
            .get<Parcels[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * parcelsService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Parcels): Observable<Parcels> {
        return this.http
            .post<Parcels>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
